# Generated by Django 4.2.7 on 2023-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('vendor_code', models.CharField(verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
