# Generated by Django 4.2.7 on 2023-11-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_myuser_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
